[connections.mysql]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "kombate"
username = "root"
password = "Dev@@5200"

[connections.mysql_2]
dialect = "mysql"
host = "prod-dev.myscriptcase.com"
port = 3306
database = "proddevm_sinan_notifica"
username = "proddevm_samuel"
password = "Gayzao123"

[connections.mysql_3]
dialect = "mysql"
host = "databasedevdb.integrator.host"
port = 3306
database = "tabelas_regulacao"
username = "samuel"
password = "Esl!FoNdZbv7ziDQ"