[connections.mysql]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "kombate"
username = "root"
password = "Dev@@5200"

[connections.mysql_2]
dialect = "mysql"
host = "prod-dev.myscriptcase.com"
port = 3306
database = "proddevm_sinan_notifica"
username = "proddevm_samuel"
password = "Gayzao123"

[connections.mysql_3]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "tabelas_regulacao"
username = "root"
password = "Dev@@5200"

[connections.mysql_4]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "ged"
username = "root"
password = "Dev@@5200"

[connections.mysql_5]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "fiscalizacao"
username = "root"
password = "Dev@@5200"


[connections.mysql_6]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "tfd"
username = "root"
password = "Dev@@5200"