[connections.mysql]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "kombate"
username = "root"
password = "Dev@@5200"

[connections.mysql_2]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "proddevm_sinan_notifica"
username = "root"
password = "Dev@@5200"

[connections.mysql_3]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "tabelas_regulacao"
username = "root"
password = "Dev@@5200"

[connections.mysql_4]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "ged"
username = "root"
password = "Dev@@5200"

[connections.mysql_5]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "fiscalizacao"
username = "root"
password = "Dev@@5200"


[connections.mysql_6]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "tfd"
username = "root"
password = "Dev@@5200"

[connections.mysql_7]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "tabelas_regulacao"
username = "root"
password = "Dev@@5200"

[connections.mysql_8]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "tuberculose"
username = "root"
password = "Dev@@5200"

[connections.mysql_9]
dialect = "mysql"
host = "185.192.96.99"
port = 3306
database = "proddevm_cirurgias"
username = "root"
password = "Dev@@5200"